name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -B build -S .
      - name: Build
        run: cmake --build build --config Release
